package statics.css;

public class MyStyle {
	public static String css = "body{\n"
			+ "    background-color: #f0f0f0;\n"
			+ "}\n"
			+ "\n"
			+ ".w-100{\n"
			+ "    width: 100%;\n"
			+ "}\n"
			+ "\n"
			+ ".w-80{\n"
			+ "    width: 80%;\n"
			+ "    margin-left:10%;\n"
			+ "}\n"
			+ "\n"
			+ ".w-40{\n"
			+ "    width: 40%;\n"
			+ "    margin-left:30%;\n"
			+ "}\n"
			+ "\n"
			+ ".w-30{\n"
			+ "    width: 30%;\n"
			+ "    margin-left: 35%;\n"
			+ "}\n"
			+ "\n"
			+ ".content{\n"
			+ "    padding: 10px;\n"
			+ "    background-color: white;\n"
			+ "}\n"
			+ "\n"
			+ ".flex-column{\n"
			+ "    display: flex;\n"
			+ "    flex-direction: column;\n"
			+ "}\n"
			+ "\n"
			+ ".grid-2{\n"
			+ "    display: grid;\n"
			+ "    grid-template-columns: auto auto;\n"
			+ "    grid-column-gap: 20px;\n"
			+ "}\n"
			+ "\n"
			+ ".btn{\n"
			+ "    border-radius: 10px;\n"
			+ "    border: none;\n"
			+ "    padding: 15px;\n"
			+ "    cursor: pointer;\n"
			+ "}\n"
			+ "\n"
			+ ".btn:hover{\n"
			+ "    background-color: #c2c2c2;\n"
			+ "}\n"
			+ "\n"
			+ ".title{\n"
			+ "    font-size:35px;\n"
			+ "    font-weight: 600;\n"
			+ "    width: 100%;\n"
			+ "    text-align: center;\n"
			+ "}\n"
			+ "\n"
			+ ".fz-25{\n"
			+ "    font-size:25px;\n"
			+ "}\n"
			+ "\n"
			+ ".mb-10{\n"
			+ "    margin-bottom:10px;\n"
			+ "}\n"
			+ "\n"
			+ ".error{\n"
			+ "    font-size:20px;\n"
			+ "    color: red;\n"
			+ "    width: 100%;\n"
			+ "    text-align: center;\n"
			+ "}\n"
			+ "\n"
			+ "table {\n"
			+ "    font-family: arial, sans-serif;\n"
			+ "    border-collapse: collapse;\n"
			+ "    width: 100%;\n"
			+ "  }\n"
			+ "  \n"
			+ "  td, th {\n"
			+ "    border: 1px solid #dddddd;\n"
			+ "    text-align: left;\n"
			+ "    padding: 8px;\n"
			+ "  }\n"
			+ "  \n"
			+ "  tr:nth-child(even) {\n"
			+ "    background-color: #dddddd;\n"
			+ "  }";
}	
